### ISSUE TITLE
Error when run test suite

### ISSUE THREAD

**Issue by AndhikaBPN** [krishna-vasudev/testng-testsuite-runner#1]
i can't user && and || in run command

error message:
At line:1 char:11
+ mvn clean && mvn test -Dname=value -Dsurefire.suiteXmlFiles=C://Users ...
+           ~~
The token '&&' is not a valid statement separator in this version.
At line:1 char:178
+ ... //test//java//com//mate//testsuite//testing.xml -f pom.xml || mvn tes ...
+                                                                ~~
The token '||' is not a valid statement separator in this version.
At line:1 char:345
+ ... //test//java//com//mate//testsuite//testing.xml -f pom.xml || mvn tes ...
+                                                                ~~
The token '||' is not a valid statement separator in this version.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : InvalidEndOfLine

**Comment by krishna-vasudev** [comment]
Please provide more information , your operating system, default vscode terminal.

**Comment by AndhikaBPN** [comment]
OS: Windows 11
Vscode version 1.93.1

**Comment by krishna-vasudev** [comment]
What is the default integrated terminal in your vscode?

**Comment by AndhikaBPN** [comment]
Powershell

**Comment by krishna-vasudev** [comment]
Just make it cmd it will work.
https://medium.com/@bhaldebraj620/running-testng-testsuite-xml-in-java-using-vscode-for-windows-automated-testing-using-selenium-482f1bac20ad

**Comment by AndhikaBPN** [comment]
Okay, sorry i didnt read the documentation. Its works now. Thanks
